name: WiFi_Tech
favicon: null
layout_spectrum: 0.7246282331179827
typography_spectrum: 0.17411322379484773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.27254642779007554
  lightness: 0.894184777745977
  saturation: 0.1457402021624148
  rhythmicContrast: 0.8786152489483356
purpose: []
